trigger:
- dev10
pr:
- dev10

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
jobs:
  - job: "LinuxDockerBuild"
    displayName: "Docker build - release"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: docker build -t seahorn/seahorn-builder:bionic-llvm10 -f docker/seahorn-builder.Dockerfile .
      - script:  docker run -v $(pwd):/host -i seahorn/seahorn-builder:bionic-llvm10 /bin/sh -c "cp build/SeaHorn*.tar.gz /host/"
      - script: docker build -t seahorn_container -f docker/seahorn.Dockerfile .
      - script: docker run -v $(pwd):/host -i seahorn_container /bin/bash -c "cd seahorn/share/seahorn && lit test/opsem"
